### ISSUE TITLE
Comentarios y correcciones 1 entrega

### ISSUE THREAD

**Issue by edjus** [LucasMontenegro1/TP2-Algoritmos3#1]
Buenas les dejo un par de comentarios y correcciones:
- [x] Limpiar el repositorio de archivos de configuración de ide's y de build: **.settings**. Organizar la carpeta src, separarlo a criterio, por ejemplo: Herramientas, Material, Jugador, etc.

- [x] Si bien está bien modelar la clase inventario, la estructura usada para almacenar no es la correcta, ya que solo permite tener un 'elemento de inventario' por posición, lo cuál no es correcto. Puedo tener por ejemplo X cantidad de Piedra, que ocupa solo un espacio en el inventario y no X espacios. Además la clase debe permitir agregar, quitar, ver la cantidad de un elemento en el inventario. La clase Stack no se usa, nombre no recomendado, Java tiene su propia clase Stack.

- [x] Error grave tener un atributo público: `public Inventario`, en la clase Jugador. Rehacer el test de jugador, nombre más descriptivo y no usando atributo público. Agregar más pruebas por ejemplo: `testCrearJugadorPoseeHachaDeDurabilidadCorrecta()`, etc.

- [x] Reorganizar las pruebas de herramientas, por ejemplo: CreacionHerramientasTest, en el mismo verificar la correcta creación de c/u de las herramientas verificar la durabilidad, fuerza, etc. En otra clase las pruebas de uso en materiales: Para cada tipo de pico lo que se espera al ser usado en cada material, nombre más descriptivos. Luego si hay alguna otra cosa que hace el Pico, se crearía otra clase probando c/u uno de los casos.

Si bien el modelo no está mal, hay algunas cosas a mejorar:

- [x] **Clase Herramienta:**
  - Debe ser abstracta y que nunca se va a tener un instancia de esa clase.
  - Código repetido en el método usar, esto se soluciona usando un método genérico `usar(Material material)`.

- [x] **Clase Desgastable:**
  - Existe código repetido en los desgastables, usar método genérico : `usarContra(Material material)` para colocar el código repetido y crear en las clases hijas aquellos métodos que tengan un comportamiento distinto, por ejemplo en HachaDeMadera `usarContra(Madera madera)`. Además en la clase PicoFino hay tres sobrecargas del método `usarContra` que no tienen implementación, esto es *"código sucio"*, significa que lo están obligando  a implementar métodos que no debería violando el principio de segregación de interfaz.

En su modelo, no están llegando a usar el patrón correctamente ya que sin no sería necesario de tener las herramientas y sus degastables: HachaDeMadera, HachaDePiedra, HachaDeHierro, etc. Aplicando correctamente doble disptach alcanzaría para solo tener herramientas y materiales.

- [x] Tratar de modelar el desgaste de la herramienta, de esa manera se puede usar un método genérico `reducirDurabilidad(int cantidadAreducir)` y que cada tipo de desgaste sepa como desgastar la herramienta, haciendo eso más lo anterior tal vez y no es necesario la Clase Desgastable.

**Comment by edjus** [comment]
Cualquier duda me escriben, saludos.

**Comment by LucasMontenegro1** [comment]
Se arreglaron
